### ISSUE TITLE
Not Find Module @shelf/jest-dynamodb in typeScript

### ISSUE THREAD

**Issue by rogeriodms** [shelfio/jest-dynamodb#104]
I run ` yarn add @shelf/jest-dynamodb --dev` and then use `import dynaJest from '@shelf/jest-dynamodb'` in my file .ts.

I received a message 'Not Find Module @shelf/jest-dynamodb'

![image](https://user-images.githubusercontent.com/46766158/129750213-2fdaadcd-f3b0-4f9c-b7ca-c6ae120dd9d3.png)

**Comment by vladgolubev** [comment]
This package has no TypeScript typings. Please suppress this error by adding `// @ts-ignore`

**Comment by vladgolubev** [comment]
Package was migrated to TypeScript, so not an issue anymore.
