### ISSUE TITLE
Encountered race condition on creation of tables

### ISSUE THREAD

**Issue by ghost** [shelfio/jest-dynamodb#117]
Sometimes when running tests, the tests fail with the following error: `ResourceNotFoundException: Cannot do operations on a non-existent table`. This happens probably 5% of the time and it happens for every test. 

I believe it is due to a race condition with the table creation. Seems like the tests run before the tables are created

Relevant dependencies:
`"@shelf/jest-dynamodb": "^1.8.1"`
`"aws-sdk": "2.998.0"`
`"jest": "27.0.6"`
`"ts-jest": "27.0.3"`

**Comment by nicholas-yong** [comment]
Also wondering how this was solved.
