### ISSUE TITLE
[Question] How can I use Jest-dynamodb in Apple Silicon?

### ISSUE THREAD

**Issue by joseph-so** [shelfio/jest-dynamodb#121]
Dynamodb-local seems to be not compatible with Apple Silicon

`Dec 24, 2021 9:26:36 PM com.almworks.sqlite4java.Internal log
WARNING: [sqlite] cannot open DB[1]: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib: dlopen(/private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib, 0x0001): tried: '/private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java-osx.dylib' (no such file)
Dec 24, 2021 9:26:36 PM com.almworks.sqlite4java.Internal log
SEVERE: [sqlite] SQLiteQueue[]: error running job queue
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib: dlopen(/private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib, 0x0001): tried: '/private/var/folders/q2/smpmq5gs1vlclkfn3s971b800000gp/T/dynamodb-local/DynamoDBLocal_lib/libsqlite4java-osx.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java-osx.dylib' (no such file)
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
	at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1441)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:282)
	at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:293)
	at com.almworks.sqlite4java.SQLiteQueue.openConnection(SQLiteQueue.java:464)
	at com.almworks.sqlite4java.SQLiteQueue.queueFunction(SQLiteQueue.java:641)
	at com.almworks.sqlite4java.SQLiteQueue.runQueue(SQLiteQueue.java:623)
	at com.almworks.sqlite4java.SQLiteQueue.access$000(SQLiteQueue.java:77)
	at com.almworks.sqlite4java.SQLiteQueue$1.run(SQLiteQueue.java:205)
	at java.base/java.lang.Thread.run(Thread.java:833) ...` 

According to the log, sqlite4java cannot find the corresponding support platform for Apple Silicon - (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')

As the last update of the sqlite4db was before Apple M1 release, Jest-dynamodb is based on dynamodb-local which is based on sqlite4db. 

Is there any suggestion on how to solve this issue? is it possible to wrap the docker version for the Jest-dynamodb? 

Thanks

**Comment by vladgolubev** [comment]
I fixed it by installing the latest Java for x86_64 architecture here: https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=x86-64-bit&package=jre

**Comment by joseph-so** [comment]
@vladgolubev Thanks, is it possible to keep both java version, or I have to replace the java by x86_64?

**Comment by vladgolubev** [comment]
Maybe it's possible, with tools like https://sdkman.io/ but I didn't try. As for me, I was happy with only 1 java version.

**Comment by joseph-so** [comment]
@vladgolubev Thanks a lot, i will have a look, as I want to only use the x86_64 in the project related to jest-dynamodb only and using the native one as much as possible

**Comment by joseph-so** [comment]
@vladgolubev, Thanks, tried SDKMan, but it is not suitable. It will install the Silicon version of Java SDK if it is available (and I cannot find the one which is not available now)

I have tried with JEnv, it fixed the issue nearly. It is better for me to start a new thread to ask the question
(jenv shell  or global are working well, but not local)

**Comment by joseph-so** [comment]
For those who read this thread, I just found the other "fix" - there is a community build for the sqlite4java for M1. Download it from https://search.maven.org/artifact/io.github.ganadist.sqlite4java/libsqlite4java-osx-arm64/1.0.392/dylib and replace ibsqlite4java-osx.dylib. (use it as your own risk)

Slightly details instruction
https://www.josephso.dev/using-jest-dynamodb-in-apple-silicon-platform-workaround/#community-build

**Comment by vladgolubev** [comment]
@joseph-so thanks for the post! I linked it in the readme https://github.com/shelfio/jest-dynamodb/blob/master/readme.md#troubleshooting

**Comment by tim-phillips** [comment]
For future readers, `jest-dynamodb` works fine on my Apple Silicon M1 machine in Oct 2022.
