### ISSUE TITLE
Cause the DB to paginate

### ISSUE THREAD

**Issue by agawley** [shelfio/jest-dynamodb#136]
I'd like to test my DB queries in the case that it has to paginate a result. I was hoping there was a way for me to cause the DB to page at a lower size than 1Mb so that I don't have to generate a bunch of data just to fill it up to cause pagination. 

Is there a way to either set the pagination size manually to a few kb or force a pagination result?

Thanks!

**Comment by vladgolubev** [comment]
Unfortunately, that goes down to the dynamodb-local core implementation. I haven't found a way to get around this by myself, so even in my tests I ended up with generating lots of mock data for such tests
