### ISSUE TITLE
Setup hangs when using custom endpoint.

### ISSUE THREAD

**Issue by babatakao** [shelfio/jest-dynamodb#160]
The `endpoint` configured in [here](https://github.com/shelfio/jest-dynamodb/blob/v3.1.2/setup.js#L23-L32) can be overridden by `jest-dynamodb-config.js`. This is typically useful for docker-compose environment.

```js
// jest-dynamodb-config.js
module.exports = () => {
  return {
    clientConfig: {
      endpoint: 'http://dynamodb:8000',
      region: 'localhost-test',
      credentials: { accessKeyId: "access-key", secretAccessKey: "secret-key" },
    },
  };
};
```

However, [`waitForLocalhost`](https://github.com/shelfio/jest-dynamodb/blob/v3.1.2/setup.js#L40) does not respect the custom endpoint config. It checks only localhost. This causes hanging-up with non-localhost endpoint.

Note that since jest-dynamodb 1.8.1 does not have `waitForLocalhost` check, custom endpoint worked well on that version. Thus, it feels like a regression for docker-compose users who do not want to launch dynamodb-local.

**Comment by harazdovskiy** [comment]
Hi @babatakao, we are working on adding TS support, this will also include a fix for the issue you mentioned!

**Comment by harazdovskiy** [comment]
@babatakao Here you can find new param and use it 🚀
1. [Readme](https://github.com/shelfio/jest-dynamodb#hostname)
2. [Types](https://github.com/shelfio/jest-dynamodb/blob/master/src/types.ts#L80)

**Comment by babatakao** [comment]
Thank you for the fix! I've confirmed the problem is resolved on my environment.

note for me: if `clientConfig.endpoint` is configured in some reason, it is also required to set `hostname`.

```js
// jest-dynamodb-config.js
module.exports = () => {
  return {
    hostname: 'dynamodb', // this is required
    clientConfig: {
      endpoint: 'http://dynamodb:8000', // if this line exists
      region: 'localhost-test',
      credentials: { accessKeyId: "access-key", secretAccessKey: "secret-key" },
    },
  };
};
```

**Comment by harazdovskiy** [comment]
Yes, you are right in order to avoid breaking changes for existing configs I added separate property instead of relying on `endpoint` in the client config.
