### ISSUE TITLE
Validation Error after updating to v3.3.1

### ISSUE THREAD

**Issue by mahdi** [shelfio/jest-dynamodb#177]
I'm receiving the following error message after updating to v3.3.1:

```
● Validation Error:

  Module ./node_modules/@shelf/jest-dynamodb/setup.js in the globalSetup option was not found.
         <rootDir> is: /Users/mahdi.taghizadeh/Gousto/repos/recommendationApi-function

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

Running `npm i` after update, removes the following files from `/node_modules/@shelf/jest-dynamodb`: setup.js / teardown.js / wait-for-localhost.js

Have I missed a breaking change between versions 3.2.0 and 3.3.1?

**Comment by vladgolubev** [comment]
See https://github.com/shelfio/jest-dynamodb/issues/171

**Comment by vladgolubev** [comment]
Try changing:
* `@shelf/jest-dynamodb/setup.js` to `@shelf/jest-dynamodb/lib/setup.js`
* `@shelf/jest-dynamodb/teardown.js` to `@shelf/jest-dynamodb/lib/teardown.js`

**Comment by mahdi** [comment]
Thanks!
