### ISSUE TITLE
Failing to create tables after launch

### ISSUE THREAD

**Issue by avnerenv0** [shelfio/jest-dynamodb#66]
This happens to us inside of Github actions, which run on some Azure instance with a strange Java version installed (Azul built for Azure instance or something like that).

So it's not clear how to fix this but it would be enough to make it work.

Right now we can see that most of the time the tables are successfully created after 6-8 retries. 
What we'd like is just to raise the max-retry configuration to ~20.
Would be best to have `jest-dynamodb` accepts some general options to pass to the DynamoDb client. Should be pretty simple.

Should I move forward and open a PR?

**Comment by vladgolubev** [comment]
Hey @avnerenv0 

I can see this as a useful feature. Feel free to proceed with a PR!

**Comment by avnerenv0** [comment]
Thanks @vladgolubev 
PR Opened
