### ISSUE TITLE
Support for aws-sdk v3

### ISSUE THREAD

**Issue by MitchWeber** [shelfio/jest-dynamodb#94]
Hi,

this repository is great. As AWS released v3 of their SDK I was wondering if there are plans to support v3 as well?

Cheers,

Michael

**Comment by vladgolubev** [comment]
I will be migrating to aws-sdk v3 as soon as X-Ray supports it. See the issue https://github.com/aws/aws-xray-sdk-node/issues/294

**Comment by WyattMufson** [comment]
@vladgolubev looks like that's merged in now

**Comment by vladgolubev** [comment]
@WyattMufson thanks for letting me know! I'll add it to my TODO list!

**Comment by diegoschacht** [comment]
Hey there! As @MitchWeber said, this repository is very good. Is there any update to support v3?
